
var links = [
	'<a href="https://www.youtube.com/watch?v=WqmrRZXxq1U">Goop Realm 5000</a>',
	'<a href="http://farchie.comicgenesis.com/">Farchie Archie</a>',
	'<a href="https://twitter.com/tripmunks">Tripmunks</a>',
	'<a href="http://monsterbreeder.com/">Monster Breeder</a>',
	'<a href="https://www.youtube.com/watch?v=5-iftiNQmjo">Chewing Gum is Really Gross</a>',
	'<a href="https://www.youtube.com/watch?v=xs_PwFWuwJs">CONCH</a>',
	'<a href="https://www.youtube.com/watch?v=r9Aj60wbP1Y">Papa Geppetto</a>',
	'<a href="https://windows95tips.com/">Windows 95 Tips</a>',
	'<a href="https://dickhealth.tumblr.com/">Dick Health</a>',
	'<a href="https://twitter.com/BotPops">Bot Pops</a>',
	'<a href="https://twitter.com/EndlessJeopardy">Endless Jeopardy</a>',
	'<a href="https://www.youtube.com/watch?v=gjileTZGHGw">Ancient Aliens demo</a>',
	'<a href="https://www.youtube.com/watch?v=p6O4ixsTT1g">Will Fluff Waffle?</a>',
	'<a href="https://sharkalien.tumblr.com/post/185090429991/neil-plays-musical-saw-september-25-2007">Neil plays musical saw</a>',
	'<a href="https://www.youtube.com/watch?v=6wl2n9dauCo">Neil Cic and Open Mike Eagle on Punch Up The Jam</a>',
	'<a href="https://www.youtube.com/watch?v=7MMxcMKW0aY">Billy Triumphs Over Evil</a>',
	'<a href="https://www.youtube.com/watch?v=b3VrAIukC-s">Why The Hell Won\'t It Snow?</a>',
	'<a href="https://youtu.be/U-9eTH62JYs">What Moustache?</a>',
	'<a href="http://www.youtube.com/watch?v=aEgMb5qip1c">Sleeping Bag</a>',
	'<a href="https://www.youtube.com/watch?v=4MXYC_jX2Wc">Splendorman</a>',
	'<a href="https://www.youtube.com/watch?v=i8NJ9jERs1E">Polysics: Ah-Yeah!!</a>',
	'<a href="https://www.youtube.com/watch?v=tiS4mFZMCT4">Polysics: Jhout</a>',
	'<a href="https://www.youtube.com/watch?v=mVKIva2KddY">Aaron</a>',
	'<a href="http://www.youtube.com/watch?v=MDS_6XbHmAk">My Benjamin Franklin</a>',
	'<a href="https://www.newgrounds.com/portal/view/112181">Facts About Presidents</a>',
	'<a href="https://www.youtube.com/watch?v=sCdlEeTQqdU">Me And My Youtube Award</a>',
	'<a href="https://www.youtube.com/watch?v=J_SSw-Ja4bw">Two and a Half Hours of MIDI</a>',
	'<a href="https://twitter.com/hintline">Hintline</a>',
	'<a href="https://twitter.com/TimAllenQuote">Tim Allen Quotes</a>',
	'<a href="https://twitter.com/goosebots">RL Stine EXE</a>',
	'<a href="https://www.youtube.com/watch?v=DOqb_UzJSUQ">Never Go On Reddit</a>',
	'<a href="https://www.youtube.com/watch?v=8t-iFr9q1I8">Lenny Kravitz: Fly Away</a>',
	'<a href="https://www.youtube.com/watch?v=TB7fqT1uAII&t=7s">Neil Cicierega, Internet Person - XOXO Festival</a>',
	'<a href="https://www.youtube.com/watch?v=BTm_RnMVbF0&feature=emb_title">Friend or Foe</a>',
	'<a href="http://www.neilcic.com/letter/">Better Letter</a>',
	'<a href="http://www.neilcic.com/0110/">0110 aka Do Not Press the Currently Selected Digit</a>',
	'<a href="https://youtu.be/bLoOnRzlV5A">Sky Blue Up</a>',
	'<a href="https://neilblr.com/post/76092422851">MOCKS YOU</a>',
	'<a href="https://youtu.be/4xElp-lYnyE">Everybody Likes You</a>',
	'<a href="https://neilblr.com/post/91162405058">Sorry For The Text Posts</a>',
	'<a href="https://youtu.be/AAGYmLLyOpI">Super Hey Ya</a>',
	'<a href="https://soundcloud.com/user-969315907/guaranteed-video-extravaganza-q-and-a">Guaranteed* Video Extravaganza Q&A bootleg</a>',
	'<a href="https://neilblr.com/post/58490668107">Ariel Needs Legs</a>',
	'<a href="https://neilblr.com/post/80311441424">Adventure game soundtrack</a>',
	'<a href="http://monsterbreeder.com/sound/">Monster Breeder soundtrack/effects</a>',
	'<a href="https://www.youtube.com/watch?v=ZI4LGTXscR4">What\'s Dylan Grillin\'?</a>',
	'<a href="https://www.youtube.com/watch?v=pvJUFGLVvGk">The McDonaldland 500</a>',
	'<a href="https://www.youtube.com/watch?v=WRjQl5NUzDg">Clark Kent</a>',
	'<a href="https://www.youtube.com/playlist?list=PL4Nm4rhtI5e7vXdVyDCgVOMf9ipX1L261">Not For Resale soundtrack</a>',
	'<a href="https://www.youtube.com/watch?v=ygI-2F8ApUM">Brodyquest</a>',
	'<a href="https://www.youtube.com/playlist?list=PL4OE-zkbHahzMB_WmYptQ2-ohM67JBqF4">Ernest Roulette</a>',
	'<a href="https://www.youtube.com/watch?v=GMh7awqGpBo&feature=emb_title">Chocolate Sauce</a>',
	'<a href="https://www.youtube.com/watch?v=tpqtQFKql_w">GameCube Controller</a>',
	'<a href="https://www.youtube.com/watch?v=uoS-mbJF8l4">Lemming Demon</a>',
	'<a href="https://www.youtube.com/watch?v=uoS-mbJF8l4">You Deliver Like a Winner</a>',
	'<a href="https://www.youtube.com/watch?v=LFCnZ4txsew&feature=youtu.be">MouthCraft (Wild Wild Fest)</a>',
	'<a href="https://neilblr.com/post/6336164676">Microkorg XL reborn as a keytar</a>',
	'<a href="https://web.archive.org/web/20120130033747/http://www.youtube.com/user/NeilCicierega">Neiltube as of 2012</a>',
	'<a href="https://www.youtube.com/watch?v=fu3ETgAvQrw">Redesign Your Logo live backing video</a>',
	'<a href="https://www.youtube.com/watch?v=9YusD8iDR8k">G*V plays a very scary game</a>',
	'<a href="https://twitter.com/neilcic/status/1181011711014383618">"mamma mia"</a>'
]